### ISSUE TITLE
Where is the telemanom module?

### ISSUE THREAD

**Issue by crystal611** [astha-chem/mvts-ano-eval#1]
What is the TelemanomAlgo content called by the module?

**Comment by astha-chem** [comment]
Hello. This repository does not provide the telemanomalgo module because it's Apache 2.0 license is complex and does not support unrestricted sharing. The original implementation by authors of that paper is here - https://github.com/khundman/telemanom

You can comment the part that calls TelemanomAlgo for the content to run. Could you also share where you found the reference? I can remove it from the repo.

**Comment by crystal611** [comment]
Where can I get the part of calling TelemanomAlgo to run the content

**Comment by lxg-scu** [comment]
> Hello. This repository does not provide the telemanomalgo module because it's Apache 2.0 license is complex and does not support unrestricted sharing. The original implementation by authors of that paper is here - https://github.com/khundman/telemanom
> 
> You can comment the part that calls TelemanomAlgo for the content to run. Could you also share where you found the reference? I can remove it from the repo.



> Hello. This repository does not provide the telemanomalgo module because it's Apache 2.0 license is complex and does not support unrestricted sharing. The original implementation by authors of that paper is here - https://github.com/khundman/telemanom
> 
> You can comment the part that calls TelemanomAlgo for the content to run. Could you also share where you found the reference? I can remove it from the repo.

src/evaluation/evaluation_utils.py  line 11,13

**Comment by lxg199788** [comment]
> Hello. This repository does not provide the telemanomalgo module because it's Apache 2.0 license is complex and does not support unrestricted sharing. The original implementation by authors of that paper is here - https://github.com/khundman/telemanom
> 
> You can comment the part that calls TelemanomAlgo for the content to run. Could you also share where you found the reference? I can remove it from the repo.

src/evaluation/evaluation_utils.py line 11,13

**Comment by crystal611** [comment]
thanks！



---Original---
From: ***@***.***&gt;
Date: Mon, Nov 8, 2021 19:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [astha-chem/mvts-ano-eval] Where is the telemanom module? (#1)




  
Hello. This repository does not provide the telemanomalgo module because it's Apache 2.0 license is complex and does not support unrestricted sharing. The original implementation by authors of that paper is here - https://github.com/khundman/telemanom
 
You can comment the part that calls TelemanomAlgo for the content to run. Could you also share where you found the reference? I can remove it from the repo.
   
Hello. This repository does not provide the telemanomalgo module because it's Apache 2.0 license is complex and does not support unrestricted sharing. The original implementation by authors of that paper is here - https://github.com/khundman/telemanom
 
You can comment the part that calls TelemanomAlgo for the content to run. Could you also share where you found the reference? I can remove it from the repo.
  
src/evaluation/evaluation_utils.py  line 11,13
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by insop** [comment]
For `TelemanomAlgo` module:

How about you could still include your wrapper class (TelemanomAlgo) with a note that the original file needs to be manually put in place from https://github.com/khundman/telemanom?

Thoughts @lxg-scu and @astha-chem ?

**Comment by astha-chem** [comment]
The challenge with providing even the wrapper for telemanom is that it is technically going to be a "derived work" and we need to provide onerous details on where each change has been made. Also just downloading the existing implementation from their library won't work with our wrapper class.
